services:
  postgres:
    image: postgres:15-alpine  # or use your custom Dockerfile
    ports:
      - "5432:5432"  # Map host port 5433 → container port 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Catin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
